global:
  smtp_smarthost: ''
  smtp_from: ''
  smtp_auth_username: ''
  smtp_auth_password: ''
  smtp_require_tls: false
route:
  group_by: ['LowRequestRate']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 1h
  receiver: 'test-mails'
receivers:
- name: 'test-mails'
  email_configs:
  - to: ""
